' <auto-generated>
' Written by the page generator. Every edit here is lost the next time the fields are
' applied. Put your own code in UserX_U.vb, which is never rewritten, and use the
' hooks at the end of this file to reach into what is generated.
' </auto-generated>
Option Strict On
Option Explicit On

Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Drawing
Imports System.Windows.Forms

Namespace SDC.Framework
    Partial Public Class UserX_U

        Private ReadOnly tableName As String = "FW_USERS"
        Private ReadOnly primaryKey As String = "UserId"
        Private ReadOnly computedFields As New HashSet(Of String)(StringComparer.OrdinalIgnoreCase) From {"FirstLast"}
        Private record As DataRow
        Private ReadOnly formBindingSource As New BindingSource()
        Private originalRowVersion As Byte()
        Private firstLastTextBox As TextBox
        Private firstNameTextBox As TextBox
        Private lastNameTextBox As TextBox
        Private address1TextBox As TextBox
        Private cityTextBox As TextBox
        Private stateTextBox As TextBox
        Private zipTextBox As TextBox
        Private emailTextBox As TextBox
        Private passwordTextBox As TextBox
        Private assignedManagerIDComboBox As ComboBox
        Private genderIDTextBox As TextBox

        ''' <summary>Builds every generated field. Called by the constructor in UserX_U.vb.</summary>
        Private Sub BuildGeneratedFields()
            ClientSize = New Size(600, 517)
            okButton.Location = New Point(ClientSize.Width - 270, ClientSize.Height - 46)
            cancelActionButton.Location = New Point(ClientSize.Width - 135, ClientSize.Height - 46)
            firstLastTextBox = AddField("FirstLast", 20, False, False)
            firstNameTextBox = AddField("FirstName", 62, False, True)
            lastNameTextBox = AddField("LastName", 104, False, True)
            address1TextBox = AddField("Address1", 146, False, False)
            cityTextBox = AddField("City", 188, False, False)
            stateTextBox = AddField("State", 230, False, False)
            zipTextBox = AddField("Zip", 272, False, False)
            emailTextBox = AddField("Email", 314, False, True)
            passwordTextBox = AddField("Password", 356, False, True)
            assignedManagerIDComboBox = AddComboField("AssignedManagerID", 398, True, 20, 320)
            genderIDTextBox = AddField("GenderID", 440, False, False)
            SetManualTabOrder(firstLastTextBox, firstNameTextBox, lastNameTextBox, address1TextBox, cityTextBox, stateTextBox, zipTextBox, emailTextBox, passwordTextBox, assignedManagerIDComboBox, genderIDTextBox, okButton, cancelActionButton)
            OnFieldsBuilt()
        End Sub

        Protected Overrides Function GetTableNameOverride() As String
            Return tableName
        End Function

        Protected Overrides Sub BindToFormInternal()
            Dim loaded = DataAccess.LoadGeneratedPageRecord(tableName, primaryKey, recordId)
            If loaded IsNot Nothing Then
                record = loaded
            Else
                Dim schema = DataAccess.GetGeneratedPageSchema(tableName)
                record = schema.NewRow()
                schema.Rows.Add(record)
            End If
            formBindingSource.DataSource = record.Table
            formBindingSource.Position = record.Table.Rows.IndexOf(record)
            For Each control In New Control() {firstLastTextBox, firstNameTextBox, lastNameTextBox, address1TextBox, cityTextBox, stateTextBox, zipTextBox, emailTextBox, passwordTextBox, genderIDTextBox}
                Dim fieldName = control.Name.Substring("TextBox_".Length)
                control.DataBindings.Clear()
                control.DataBindings.Add("Text", formBindingSource, fieldName, True, DataSourceUpdateMode.Never)
                If record.Table.Columns.Contains(fieldName) Then control.Text = If(record(fieldName) Is DBNull.Value, String.Empty, Convert.ToString(record(fieldName)))
            Next
            ConfigureLookupCombo(assignedManagerIDComboBox, DataAccess.GetLookupTable("FW_Users", "UserId", "FirstLast", True), "UserId", "FirstLast", CurrentLookupId("AssignedManagerID"))
            If record.Table.Columns.Contains("RowVersion") AndAlso Not record.IsNull("RowVersion") Then originalRowVersion = CType(DirectCast(record("RowVersion"), Byte()).Clone(), Byte())
            CaptureOriginalRowVersion(originalRowVersion)
            OnRecordBound()
        End Sub

        ''' <summary>
        ''' The key and any computed column are shown but never edited. Typing into a computed
        ''' column invites a value the database would refuse and then discard.
        ''' </summary>
        Protected Overrides Sub ApplyMode()
            For Each control In Controls.OfType(Of TextBox)()
                Dim columnName = If(control.Name.StartsWith("TextBox_", StringComparison.OrdinalIgnoreCase), control.Name.Substring("TextBox_".Length), String.Empty)
                Dim isComputed = computedFields.Contains(columnName)
                control.ReadOnly = String.Equals(columnName, primaryKey, StringComparison.OrdinalIgnoreCase) OrElse isComputed
                If isComputed Then ShowComputedFieldHint(control)
            Next
        End Sub

        Private Function CurrentLookupId(fieldName As String) As Integer
            If record Is Nothing OrElse record.Table Is Nothing OrElse Not record.Table.Columns.Contains(fieldName) OrElse record.IsNull(fieldName) Then Return 0
            Dim value As Integer
            Return If(Integer.TryParse(Convert.ToString(record(fieldName)), value), value, 0)
        End Function

        Protected Overrides Function SaveRecord() As Boolean
            Dim values As New Dictionary(Of String, Object)(StringComparer.OrdinalIgnoreCase)
            values("FirstLast") = firstLastTextBox.Text
            values("FirstName") = firstNameTextBox.Text
            values("LastName") = lastNameTextBox.Text
            values("Address1") = address1TextBox.Text
            values("City") = cityTextBox.Text
            values("State") = stateTextBox.Text
            values("Zip") = zipTextBox.Text
            values("Email") = emailTextBox.Text
            values("Password") = passwordTextBox.Text
            values("AssignedManagerID") = GetComboSelectedIdOrNull(assignedManagerIDComboBox)
            values("GenderID") = genderIDTextBox.Text
            OnBeforeSave(values)
            Dim savedId As Integer = recordId
            If savedId <= 0 AndAlso record.Table.Columns.Contains(primaryKey) AndAlso Not record.IsNull(primaryKey) Then Integer.TryParse(Convert.ToString(record(primaryKey)), savedId)
            Dim updatedBy = If(SessionState.IsActive, SessionState.Current.Value.UserID, 0)

            Dim outcome As SaveResult
            Dim savedRecordId = DataAccess.TrySaveGeneratedPageRecord(tableName, primaryKey, savedId, values, originalRowVersion, updatedBy, outcome)

            If outcome = SaveResult.RecordDeleted Then
                MessageBox.Show(Me, "The record no longer exists.", "Save Failed", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                Return False
            End If

            ' A conflict is the user's decision, never last-saved-wins. Declining keeps the
            ' page open with the edits intact.
            If outcome = SaveResult.RecordChanged Then
                If Not ConfirmConcurrencyOverwrite() Then Return False

                Dim latest = DataAccess.LoadGeneratedPageRecord(tableName, primaryKey, savedId)
                If latest Is Nothing Then
                    MessageBox.Show(Me, "The record no longer exists.", "Save Failed", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                    Return False
                End If

                originalRowVersion = If(latest.Table.Columns.Contains("RowVersion") AndAlso Not latest.IsNull("RowVersion"),
                                        CType(DirectCast(latest("RowVersion"), Byte()).Clone(), Byte()), Nothing)
                CaptureOriginalRowVersion(originalRowVersion)
                savedRecordId = DataAccess.TrySaveGeneratedPageRecord(tableName, primaryKey, savedId, values, originalRowVersion, updatedBy, outcome)
            End If

            If outcome <> SaveResult.Succeeded OrElse savedRecordId <= 0 Then Return False
            If record Is Nothing OrElse Not record.Table.Columns.Contains(primaryKey) Then Return False
            record(primaryKey) = savedRecordId
            Return True
        End Function

        Protected Overrides Function ResolveAuditRecordKey() As String
            Return If(record Is Nothing OrElse record.Table Is Nothing OrElse Not record.Table.Columns.Contains(primaryKey) OrElse record.IsNull(primaryKey), String.Empty, Convert.ToString(record(primaryKey)))
        End Function

        ' Hooks. Implement any of these in UserX_U.vb to reach into what is generated
        ' above. One nobody implements compiles away to nothing, so a page that uses none of
        ' them carries no cost. They are Subs because VB partial methods cannot return a value -
        ' to refuse a save, override TryBuildRecord, which FW_Base_U already calls for that.

        ''' <summary>Every generated control exists and the tab order is set.</summary>
        Partial Private Sub OnFieldsBuilt()
        End Sub

        ''' <summary>The record is loaded and every generated control is bound to it.</summary>
        Partial Private Sub OnRecordBound()
        End Sub

        ''' <summary>The values are built and nothing is written yet. Add, change or remove entries.</summary>
        Partial Private Sub OnBeforeSave(values As Dictionary(Of String, Object))
        End Sub
    End Class
End Namespace
