' <auto-generated>
' Written by the page generator. Every edit here is lost the next time the fields
' are applied. Put your own code in FW_Employees_U.vb, which is never rewritten,
' and use the hooks at the end of this file to reach into what is generated.
' </auto-generated>
Option Strict On
Option Explicit On

Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Drawing
Imports System.Windows.Forms

Namespace SDC.Framework
    Partial Public Class FW_Employees_U

        Private ReadOnly tableName As String = "FW_Employees"
        Private ReadOnly primaryKey As String = "EmployeeID"
        Private ReadOnly computedFields As New HashSet(Of String)(StringComparer.OrdinalIgnoreCase)
        Protected ReadOnly GeneratedFieldsBottom As Integer = 566
        Private record As DataRow
        Private ReadOnly formBindingSource As New BindingSource()
        Private originalRowVersion As Byte()
        Private lastSavedRecordId As Integer
        Private zipCoderController As ZipCoderController
        Private smartyAddressLookupController As SmartyAddressLookupController
        Private firstNameTextBox As TextBox
        Private lastNameTextBox As TextBox
        Private address1TextBox As TextBox
        Private address2TextBox As TextBox
        Private cityTextBox As TextBox
        Private stateTextBox As TextBox
        Private zipTextBox As TextBox
        Private userNameTextBox As TextBox
        Private passwordTextBox As TextBox
        Private genderIDComboBox As ComboBox
        Private emailTextBox As TextBox
        Private receivesHealthAlertsCheckBox As CheckBox
        Private isActiveCheckBox As CheckBox
        Private birthDateDateTimePicker As DateTimePicker
        Private hireDateDateTimePicker As DateTimePicker
        Private terminationDateDateTimePicker As DateTimePicker
        Private homePhoneTextBox As TextBox
        Private cellPhoneTextBox As TextBox
        Private workPhoneTextBox As TextBox
        Private extensionTextBox As TextBox
        Private assignedManagerIDComboBox As ComboBox
        Private timeZoneIDComboBox As ComboBox

        ''' <summary>
        ''' Every control on the page, laid out. Called from the constructor in FW_Employees_U.vb.
        ''' </summary>
        Private Sub BuildGeneratedFields()
            ClientSize = New Size(1060, 799)
            okButton.Location = New Point(ClientSize.Width - 270, ClientSize.Height - 46)
            cancelActionButton.Location = New Point(ClientSize.Width - 135, ClientSize.Height - 46)
            firstNameTextBox = AddField("FirstName", 20, False, True, 20)
            lastNameTextBox = AddField("LastName", 62, False, True, 20)
            address1TextBox = AddField("Address1", 104, False, False, 20)
            address2TextBox = AddField("Address2", 146, False, False, 20)
            cityTextBox = AddField("City", 188, False, False, 20)
            stateTextBox = AddField("State", 230, False, False, 20)
            zipTextBox = AddField("Zip", 272, False, False, 20)
            ' (blank line 1) - vertical space, no control
            userNameTextBox = AddField("UserName", 356, False, True, 20)
            passwordTextBox = AddField("Password", 398, False, True, 20)
            genderIDComboBox = AddComboField("GenderID", 440, False, 20, 320)
            emailTextBox = AddField("Email", 482, False, True, 20)
            receivesHealthAlertsCheckBox = AddCheckField("ReceivesHealthAlerts", 524, 20)
            isActiveCheckBox = AddCheckField("IsActive", 20, 580)
            birthDateDateTimePicker = AddDateField("BirthDate", 62, False, 580, True, False)
            hireDateDateTimePicker = AddDateField("HireDate", 104, False, 580, True, False)
            terminationDateDateTimePicker = AddDateField("TerminationDate", 146, False, 580, True, False)
            Controls.Add(New Label() With {
                .Name = "Label_Divider1",
                .AutoSize = False,
                .Text = String.Empty,
                .Location = New Point(580, 188),
                .Size = New Size(450, 2),
                .BackColor = SystemColors.ControlDark
            })
            DeclareUnboundField("Label_Divider1", "A dividing line between groups of fields. It names no column.")
            homePhoneTextBox = AddField("HomePhone", 230, False, False, 580)
            cellPhoneTextBox = AddField("CellPhone", 272, False, False, 580)
            workPhoneTextBox = AddField("WorkPhone", 314, False, False, 580)
            extensionTextBox = AddField("Extension", 356, False, False, 580)
            assignedManagerIDComboBox = AddComboField("AssignedManagerID", 398, False, 580, 320)
            timeZoneIDComboBox = AddComboField("TimeZoneID", 440, False, 580, 320)
            SetManualTabOrder(firstNameTextBox, lastNameTextBox, address1TextBox, address2TextBox, cityTextBox, stateTextBox, zipTextBox, userNameTextBox, passwordTextBox, genderIDComboBox, emailTextBox, receivesHealthAlertsCheckBox, isActiveCheckBox, birthDateDateTimePicker, hireDateDateTimePicker, terminationDateDateTimePicker, homePhoneTextBox, cellPhoneTextBox, workPhoneTextBox, extensionTextBox, assignedManagerIDComboBox, timeZoneIDComboBox, okButton, cancelActionButton)
            ApplyMode()
            smartyAddressLookupController = New SmartyAddressLookupController(
                Me,
                address1TextBox,
                cityTextBox,
                stateTextBox,
                zipTextBox,
                Function() SmartyAddressLookupController.IsSessionLookupEnabled(),
                Function() SmartyAddressLookupController.GetSessionEmbeddedKey())
            zipCoderController = New ZipCoderController(Me, cityTextBox, stateTextBox, zipTextBox)

            OnFieldsBuilt()
        End Sub

        Protected Overrides Function GetTableNameOverride() As String
            Return tableName
        End Function

        Protected Overrides Sub BindToFormInternal()
            Dim loaded = DataAccess.LoadGeneratedPageRecord(tableName, primaryKey, recordId)
            If loaded IsNot Nothing Then
                record = loaded
            Else
                Dim schema = DataAccess.GetGeneratedPageSchema(tableName)
                record = schema.NewRow()
                schema.Rows.Add(record)
            End If
            formBindingSource.DataSource = record.Table
            formBindingSource.Position = record.Table.Rows.IndexOf(record)
            For Each control In New Control() {firstNameTextBox, lastNameTextBox, address1TextBox, address2TextBox, cityTextBox, stateTextBox, zipTextBox, userNameTextBox, passwordTextBox, emailTextBox, homePhoneTextBox, cellPhoneTextBox, workPhoneTextBox, extensionTextBox}
                Dim fieldName = control.Name.Substring("TextBox_".Length)
                control.DataBindings.Clear()
                control.DataBindings.Add("Text", formBindingSource, fieldName, True, DataSourceUpdateMode.Never)
                If record.Table.Columns.Contains(fieldName) Then control.Text = If(record(fieldName) Is DBNull.Value, String.Empty, Convert.ToString(record(fieldName)))
            Next
            If record.Table.Columns.Contains("BirthDate") Then SetDateField(birthDateDateTimePicker, record("BirthDate"))
            If record.Table.Columns.Contains("HireDate") Then SetDateField(hireDateDateTimePicker, record("HireDate"))
            If record.Table.Columns.Contains("TerminationDate") Then SetDateField(terminationDateDateTimePicker, record("TerminationDate"))
            If record.Table.Columns.Contains("ReceivesHealthAlerts") Then SetCheckField(receivesHealthAlertsCheckBox, record("ReceivesHealthAlerts"))
            If record.Table.Columns.Contains("IsActive") Then SetCheckField(isActiveCheckBox, record("IsActive"))
            ConfigureLookupCombo(genderIDComboBox, DataAccess.GetLookupTable("FW_Gender", "GenderID", "GenderDescription", True, CurrentLookupId("GenderID")), "GenderID", "GenderDescription", CurrentLookupId("GenderID"))
            ConfigureLookupCombo(assignedManagerIDComboBox, DataAccess.GetLookupTable("FW_Employees", "EmployeeID", "FirstLast", True, CurrentLookupId("AssignedManagerID")), "EmployeeID", "FirstLast", CurrentLookupId("AssignedManagerID"))
            ConfigureLookupCombo(timeZoneIDComboBox, DataAccess.GetLookupTable("FW_TimeZones", "TimeZoneID", "DisplayName", False, CurrentLookupId("TimeZoneID")), "TimeZoneID", "DisplayName", CurrentLookupId("TimeZoneID"))
            If record.Table.Columns.Contains("RowVersion") AndAlso Not record.IsNull("RowVersion") Then originalRowVersion = CType(DirectCast(record("RowVersion"), Byte()).Clone(), Byte())
            CaptureOriginalRowVersion(originalRowVersion)

            OnRecordBound()
        End Sub

        ''' <summary>
        ''' The key and any computed column are shown but never edited. Typing into a computed
        ''' column invites a value the database would refuse and then discard.
        ''' </summary>
        Protected Overrides Sub ApplyMode()
            For Each control In Controls.OfType(Of TextBox)()
                Dim columnName = If(control.Name.StartsWith("TextBox_", StringComparison.OrdinalIgnoreCase), control.Name.Substring("TextBox_".Length), String.Empty)
                Dim isComputed = computedFields.Contains(columnName)
                control.ReadOnly = String.Equals(columnName, primaryKey, StringComparison.OrdinalIgnoreCase) OrElse isComputed
                If isComputed Then ShowComputedFieldHint(control)
            Next
        End Sub

        Protected Overrides Function TryBuildRecord() As Boolean
            Dim allowSave = True
            OnValidating(allowSave)
            Return allowSave
        End Function

        ''' <summary>Warns before discarding edits. Without this Cancel would discard silently.</summary>
        Protected Overrides Function ShouldWarnOnCancel() As Boolean
            Return True
        End Function

        ''' <summary>
        ''' Field-level permissions choose Can_Create over Can_Update from this. Without it
        ''' every new record would be evaluated as an update and Can_Create would never apply.
        ''' </summary>
        Protected Overrides Function IsCreatingNewRecord() As Boolean
            Return recordId <= 0
        End Function

        Private Function CurrentLookupId(fieldName As String) As Integer
            If record Is Nothing OrElse record.Table Is Nothing OrElse Not record.Table.Columns.Contains(fieldName) OrElse record.IsNull(fieldName) Then Return 0
            Dim value As Integer
            Return If(Integer.TryParse(Convert.ToString(record(fieldName)), value), value, 0)
        End Function

        Protected Overrides Function SaveRecord() As Boolean
            Dim values As New Dictionary(Of String, Object)(StringComparer.OrdinalIgnoreCase)
            values("FirstName") = firstNameTextBox.Text
            values("LastName") = lastNameTextBox.Text
            values("Address1") = address1TextBox.Text
            values("Address2") = address2TextBox.Text
            values("City") = cityTextBox.Text
            values("State") = stateTextBox.Text
            values("Zip") = zipTextBox.Text
            values("UserName") = userNameTextBox.Text
            values("Password") = passwordTextBox.Text
            values("GenderID") = GetComboSelectedIdOrNull(genderIDComboBox)
            values("Email") = emailTextBox.Text
            values("ReceivesHealthAlerts") = CheckFieldValue(receivesHealthAlertsCheckBox)
            values("IsActive") = CheckFieldValue(isActiveCheckBox)
            values("BirthDate") = DateFieldValue(birthDateDateTimePicker)
            values("HireDate") = DateFieldValue(hireDateDateTimePicker)
            values("TerminationDate") = DateFieldValue(terminationDateDateTimePicker)
            values("HomePhone") = homePhoneTextBox.Text
            values("CellPhone") = cellPhoneTextBox.Text
            values("WorkPhone") = workPhoneTextBox.Text
            values("Extension") = extensionTextBox.Text
            values("AssignedManagerID") = GetComboSelectedIdOrNull(assignedManagerIDComboBox)
            values("TimeZoneID") = GetComboSelectedIdOrNull(timeZoneIDComboBox)

            OnBeforeSave(values)

            Dim savedId As Integer = recordId
            If savedId <= 0 AndAlso record.Table.Columns.Contains(primaryKey) AndAlso Not record.IsNull(primaryKey) Then Integer.TryParse(Convert.ToString(record(primaryKey)), savedId)
            ' The acting user: while an administrator views as somebody else, the
            ' change is theirs and is stamped with their id.
            Dim updatedBy = SessionState.ActingUserID

            Dim outcome As SaveResult
            Dim savedRecordId = DataAccess.TrySaveGeneratedPageRecord(tableName, primaryKey, savedId, values, originalRowVersion, updatedBy, outcome)

            If outcome = SaveResult.RecordDeleted Then
                MessageBox.Show(Me, "The record no longer exists.", "Save Failed", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                Return False
            End If

            ' A conflict is the user's decision, never last-saved-wins. Declining keeps the
            ' page open with the edits intact.
            If outcome = SaveResult.RecordChanged Then
                If Not ConfirmConcurrencyOverwrite() Then Return False

                Dim latest = DataAccess.LoadGeneratedPageRecord(tableName, primaryKey, savedId)
                If latest Is Nothing Then
                    MessageBox.Show(Me, "The record no longer exists.", "Save Failed", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                    Return False
                End If

                originalRowVersion = If(latest.Table.Columns.Contains("RowVersion") AndAlso Not latest.IsNull("RowVersion"),
                                        CType(DirectCast(latest("RowVersion"), Byte()).Clone(), Byte()), Nothing)
                CaptureOriginalRowVersion(originalRowVersion)
                savedRecordId = DataAccess.TrySaveGeneratedPageRecord(tableName, primaryKey, savedId, values, originalRowVersion, updatedBy, outcome)
            End If

            If outcome <> SaveResult.Succeeded OrElse savedRecordId <= 0 Then Return False
            If record Is Nothing OrElse Not record.Table.Columns.Contains(primaryKey) Then Return False
            record(primaryKey) = savedRecordId
            lastSavedRecordId = savedRecordId
            Return True
        End Function

        ''' <summary>
        ''' The record this page saved, so a browse page can select it after a Create.
        ''' Zero until something is saved, which is what FW_Base_B falls back on.
        ''' </summary>
        Public Overrides ReadOnly Property SavedRecordId As Integer
            Get
                Return lastSavedRecordId
            End Get
        End Property

        Protected Overrides Function ResolveAuditRecordKey() As String
            Return If(record Is Nothing OrElse record.Table Is Nothing OrElse Not record.Table.Columns.Contains(primaryKey) OrElse record.IsNull(primaryKey), String.Empty, Convert.ToString(record(primaryKey)))
        End Function

        ' Hooks. Implement any of these in FW_Employees_U.vb to reach into what is
        ' generated above. One nobody implements compiles away to nothing, and a page
        ' using none of them carries no cost at all.

        ''' <summary>Every generated control exists and the tab order is set.</summary>
        Partial Private Sub OnFieldsBuilt()
        End Sub

        ''' <summary>The record is loaded and every generated control is bound to it.</summary>
        Partial Private Sub OnRecordBound()
        End Sub

        ''' <summary>
        ''' A save has been asked for and nothing is written yet. Set allowSave to False
        ''' to refuse it, which leaves the page open with its edits intact.
        '''
        ''' ByRef rather than a return value, because a VB partial method cannot return
        ''' one - an unimplemented partial method leaves no call site to take a result
        ''' from.
        ''' </summary>
#Disable Warning BC40005 ' Deliberate: this hook hides Control.OnValidating, as the summary says.
        Partial Private Sub OnValidating(ByRef allowSave As Boolean)
        End Sub
#Enable Warning BC40005

        ''' <summary>The values are built and nothing is written. Add, change or remove entries.</summary>
        Partial Private Sub OnBeforeSave(values As Dictionary(Of String, Object))
        End Sub
    End Class
End Namespace
